services:
  # nginx:
  #   image: nginx:1.21.6-alpine
  #   container_name: api_nginx
  #   ports:
  #     - 80:80
  #     # - 443:443
  #     - 5055:5055
  #     - 8080:8080
  #   # volumes:
  #   #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   #   - ./nginx/certs/server.pem:/etc/nginx/certs/nginx.key
  #   #   - ./nginx/certs/server.crt:/etc/nginx/certs/nginx.crt
  #   #   - ./web/index.html:/var/www/index.html
  #   #   - ./pdf:/var/www/pdf
  #   depends_on:
  #     - go_app

  nginx:
    build: nginx
    container_name: nginx_web
    ports:
      - 8088:8088
      # - 443:443
    restart: unless-stopped
    depends_on:
      - go_app

  nginx_1:
    build: nginx/nginx_1
    container_name: nginx_1_api
    ports:
      - 5050:5050
    restart: unless-stopped
    depends_on:
      - go_app

  nginx_2:
    build: nginx/nginx_2
    container_name: nginx_2_api
    ports:
      - 5051:5051
    restart: unless-stopped
    depends_on:
      - go_app

  go_app:
    build: go
    container_name: go-app
    restart: unless-stopped
    depends_on:
      - db

  db:
    build: database
    container_name: mysql
    env_file: .env
    environment:
      # MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
    restart: unless-stopped

  # db:
  #   image: mysql:8.0
  #   container_name: mysql
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     # MYSQL_ROOT_PASSWORD: 1234
  #     # MYSQL_DATABASE: test_db
  #     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  #     MYSQL_DATABASE: "${MYSQL_DATABASE}"
  #   # volumes:
  #     # - ./data/mysql/log:/var/log/mysql
  #   #   - db_data:${MARIADB_DATA_DIR}
  #   #   - db_logs:${MARIADB_LOG_DIR}
  #     # - ./database:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306